.github/ISSUE_TEMPLATE/BUG_REPORT.md
.github/ISSUE_TEMPLATE/FEATURE_REQUEST.md

Almost positive this is needed for them to be recognized as issue templates.

Add front matter to issue templates

---

.github/workflows/validate-new-issue-test.yml
.github/workflows/validate-new-issue.yml

This is a first PR towards figuring out how to do automated testing, CI, and deployment for GitHub Actions.
I'm trying to wrap my head around this.
Reticketed the bigger picture as https://github.com/getsentry/.github/issues/22.

Write a workflow test

---

.github/workflows/test-helpers/get-issue-validation-log
.github/workflows/validate-new-issue-test.yml
.github/workflows/validate-new-issue.yml

Part of https://github.com/getsentry/.github/issues/26.
- Adds a test for the primary case: closing invalid issues.
- Fixes bug where we were never rejecting any issues because the headings-less `FEATURE_REQUEST.md` template would always match.
- Futzes with log futzing a bit (larger discussion re: testing strategy noted at https://github.com/getsentry/.github/issues/22#issuecomment-769933913).

Ignore empty templates during validation

---

.github/workflows/validate-new-issue-test.yml
.github/workflows/validate-new-issue.yml

Fixes #62.
Relaxes validation bot to only look for a single matching header instead of all headers in the template.

ref(validation): Relax validation bot

---

.github/workflows/issue-status-helper.yml

We have so many labels on getsentry/sentry so we need to tell `gh` to `--paginate` to get all of them. We already do this in the routing helper but not in this one causing issues.

fix(status_label_helper): Get all labels via --paginate

---

.github/workflows/issue-routing-helper.yml

Fixes #68 by ignoring issues that already have `Status: Backlog` or `Status: In Progress` label when routing. Note that this also skips the `@team` mention comment.

feat(router): Ignore triaged issues

---

.github/workflows/stale.yml

This was deployed manually, bringing upstream into .github to align with other bots.
https://github.com/getsentry/sentry/blob/master/.github/workflows/stale.yml
https://github.com/getsentry/sentry-docs/blob/master/.github/workflows/stale.yml
https://github.com/getsentry/onpremise/blob/master/.github/workflows/stale.yml

Upstream stalebot

---

.github/workflows/issue-routing-helper.yml

Fixes #72.
Untested as promised, @BYK.
(Tested manually though: [labeled](https://github.com/getsentry/.github-chadwhitacre/issues/695#event-5124482871), [skipped](https://github.com/getsentry/.github-chadwhitacre/runs/3265396317?check_suite_focus=true)).

Ignore closed issues in routing helper

---

.github/workflows/issue-routing-helper.yml

Explicitly handle error statuses from `gh api` instead of detecting error conditions by inspecting the first character of the output. It is not guaranteed that the first character of an errored `gh api` response is `{`, but it's definitely guaranteed that in case of HTTP 4xx–5xx responses, `gh api` will exit with a nonzero status. This approaches uses the failing status to blank out the `mention_slug` variable, which I find to be less hacky and more future-proof.
Additionally, this avoids GitHub Actions workflow interpolation `${{...}}` embedded in bash script and instead passes in variables as environment variables. The bash script may fail after expanding these placeholders if any of the expanded value contains characters like `"'${}!` or similar characters that have special meaning in …

Improve error handling around gh api

---

SUPPORT.md

Follow-up to #100, where I learned about this file. :P
Now that we have a process in place for [routing and triaging](https://open.sentry.io/triage/) GitHub Issues, I think we can remove this file, the purpose of which is to [put a little help text prompt](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/adding-support-resources-to-your-project) when people are opening new GitHub issues. We used to want people to not open issues with us but now we want them to.
Thoughts @drguthals @souredoutlook?

Remove SUPPORT.md

---

SECURITY.md

Adjusts our standard SECURITY.md policy to suggest reporting vulnerabilities via [GitHub's new feature](https://docs.github.com/en/code-security/security-advisories/guidance-on-reporting-and-writing/privately-reporting-a-security-vulnerability).

policy(security): include reporting via GH's private vulnerability reporting feature

---

.github/workflows/issue-routing-helper.yml

Fixes the issue for github actions where issues opened by sentry members are still getting routed.
https://github.com/getsentry/eng-pipes/issues/355

Check for sentry member/owner for issue author before introducing routing logic

---

SECURITY.md

The private reporting feature could still use some work, so I'd like to not _officially_ recommend it in our security policy.

removed instructions to use gh's private reporting

---

.github/ISSUE_TEMPLATE/BUG_REPORT.md

Too often, the first thing we have to do is ask for debug logs.

Ask for logs in bug issue template

---

.github/ISSUE_TEMPLATE/BUG_REPORT.md

Reverts getsentry/.github#114 ... should override in `sentry-cli` vs. modifying global template.

Revert "Ask for logs in bug issue template"

---

.github/workflows/secret-scan.yml

Sentry uses GH's Secret Scanning on our public repositories, including their push protection to prevent secret leaks.
However, this does not cover private repositories without an expensive GHAS license. With this org-wide workflow, this will ensure secret scanning occurs on pull requests whether they're in a private or public repository. 
This workflow does not pull the full commit history but just the current default branch + 2 commit to make sure scanning stays speedy. As a result, this won't detect secrets already committed to private repos, but we're working through any of those in a separate work stream.

security: org-wide secret scanning

---

.github/workflows/secret-scan.yml

Most of the Datadog secrets that are flagged are the DSN-like tokens that do not have access to anything other than collecting data.
Excluding the detector to reduce noises.

fix(secret scanner): Exclude datadog detector

---

.github/workflows/secret-scan.yml

Bumps TruffleHog to the latest version.

ci(trufflehog): bump to 3.80.3

---

.github/workflows/secret-scan.yml

- Send all scanning events to panther
- remove redundant double-quote
- bump trufflehog to 3.82.13
- Add missing double-quote for createAt

Update Secret Scan Log Forwarding

---

.github/workflows/secret-scan.yml

Due to security design in GitHub, the `vars.SECRET_SCAN_PANTHER_WEBHOOK_URL` will not be exposed to outside collaborators who open PRs on our repos, which cause the secret scanner to fail.
Adding an if statement and do nothing if the var is not available.

fix(secret-scan): skip curl if env var not available

---

.github/workflows/secret-scan.yml

Using [v3.88.11](https://github.com/trufflesecurity/trufflehog/releases/tag/v3.88.11) now, this will add support to our new Sentry Token format

chores(secret_scan): Update Trufflehog to latest version 

---

.github/workflows/enforce-license-compliance.yml
.github/workflows/secret-scan.yml

- Update TruffleHog to 3.88.20 (includes the new Sentry token formats!)
- Pin version references GitHub Actions to defend against dependency attacks.

chore: update trufflehog and pin actions

---

.github/workflows/secret-scan.yml

Dual syncing with our old and new SIEM before deprecating the old. Don't merge until the new org-wide variable is added.

Add second destination for secret-scan output

---

.github/workflows/secret-scan.yml

Update trufflehog to the latest available version, 3.89.2.

chore: update trufflehog to 3.89.2
