- ISSUE_TEMPLATE/BUG_REPORT.md
- ISSUE_TEMPLATE/FEATURE_REQUEST.md
- ISSUE_TEMPLATE/QUESTION.md
This will affect the whole org so I expect some discussion before we do anything.
Let's get it started.
Also worth noting that the template takes effect in repos that don't have already a template. It's just a default.
> some issue templates

- .github/workflows/greet.yml
> Test out global workflows

- .github/ISSUE_TEMPLATE/BUG_REPORT.md
- .github/workflows/test-helpers/get-issue-validation-log
- .github/workflows/validate-new-issue-test.yml
- .github/workflows/validate-new-issue.yml
Closes #15.
Test run: https://github.com/getsentry/.github-chadwhitacre/actions/runs/509428606.
> Relax issue validation

- .github/workflows/test-helpers/get-issue-validation-log
- .github/workflows/validate-new-issue-test.yml
- .github/workflows/validate-new-issue.yml
- close tickets that are unchanged templates (#26)
- use the new `gh issue comment` cli (#25)
- serialize to work around race condition in tests (#30)
> Template validation improvements

- .github/workflows/test-helpers/get-issue-validation-log
- .github/workflows/validate-new-issue-test.yml
> Serialize tests to work around race condition

- .github/workflows/validate-new-issue-test.yml
- .github/workflows/validate-new-issue.yml
> Use new `gh issue comment` cli

- .github/workflows/validate-new-issue-test.yml
- .github/workflows/validate-new-issue.yml
> Fail on exact template match

- .github/workflows/validate-new-issue-test.yml
- .github/workflows/validate-new-issue.yml
See example failed issue: getsentry/onpremise#847
> fix(template-validator): Normalize CRLF, don't put JSON in comments

- .github/workflows/test-helpers/get-issue-validation-log
- .github/workflows/validate-new-issue-test.yml
- .github/workflows/validate-new-issue.yml
> gha(validation): Reject empty issues (ignoring whitespace)

- .github/workflows/validate-new-issue-test.yml
- .github/workflows/validate-new-issue.yml
> Apply Unrouted label to validated issues

- .github/workflows/test-helpers/make-issue
- .github/workflows/test-helpers/wait-for-issue
- .github/workflows/validate-new-issue-test.yml
> Rewrite tests to use actual issue state vs. logs

- .github/workflows/test-helpers/make-issue
- .github/workflows/validate-new-issue-test.yml
- .github/workflows/validate-new-issue.yml
We invite bot bug reports in the close comment, but then we've been immediately closing the bot bug reports! 😖 https://github.com/getsentry/.github/issues/50 https://github.com/getsentry/.github/issues/49 https://github.com/getsentry/.github/issues/48 https://github.com/getsentry/.github/issues/43 https://github.com/getsentry/.github/issues/39
> Special-case validation bot bug reports

- .github/workflows/triage-helper.yml
Part of https://app.asana.com/0/1200204899441683/1200248184946932/f
Test runs: getsentry/release-tester#1
> feat: Add triage label helper

- .github/workflows/issue-routing-helper.yml
Part of https://app.asana.com/0/1200204899441683/1200248184946932/f
Test runs: getsentry/release-tester#1
> feat: Add issue routing helper

- .github/workflows/issue-routing-helper.yml
Kinda WET and hacky but this fixes https://github.com/getsentry/.github/issues/77.
> Fix routing helper

- .github/workflows/enforce-license-compliance.yml
cf. https://github.com/prisma/prisma-examples/pull/1999/files
This is probably worth doing for other workflows (haven't checked) but keeping scope focused for now.
> Avoid running in forks

- .github/workflows/enforce-license-compliance.yml
https://github.com/getsentry/sentry-docs/blob/master/.github/workflows/enforce-license-compliance.yml
> Upstream FOSSA refactor from sentry-docs

- .github/workflows/enforce-license-compliance.yml
> Fix sloppiness

- PULL_REQUEST_TEMPLATE.md
> Be explicit about who "you" is

- .github/workflows/FOSSA_API_KEY
This is no longer needed as of #87
> Remove FOSSA_API_KEY

- SECURITY.md
Just an initial SECURITY.md policy for our repos to provide easy-to-find instructions on reporting security issues.
We will expand on this in the future as our security program with the community matures. 😄
> Initial SECURITY.md policy

- .github/ISSUE_TEMPLATE/BUG_REPORT.md
@dcramer points out that this isn't relevant in e.g. Vanguard
> Genericize bug template

- .github/workflows/secret-scan.yml
Removing the fancy fetch depth logic. This will increase runtimes of the action, but should provide more consistent results.
> fix: secret scanning remove fetch depth

- .github/workflows/secret-scan.yml
Requires https://github.com/getsentry/security-as-code/pull/989 to be merged first
Custom log source created in Panther, example log:
```
{
"event":"github_secret_scanning_failed",
createdAt:"2024-09-26T08:48:54Z",
"repo":"getsentry/jeffrey_test",
"pull_request":"https://github.com/getsentry/jeffrey_test/pull/11"",
"actor":"Jeffreyhung" 
}
```
> feat(secret-scanning): Forward alerts to Panther

- .github/workflows/secret-scan.yml
Add `continue-on-error` so that the log forwarding will be triggered when secret are found
> fix(secret scanning): add continue-on-error

- .github/workflows/dependency-review.yml
Adds support for local repos to provide their own dependency review configuration under special circumstances.
> support dependency review config

- .github/workflows/secret-scan.yml
Allow the workflow to run on merge queues
> fix(secret scanning): Add merge_queue trigger
